### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Abdul-majid-ashrafi** [TeamClouders/tutor-app12#1]
![one](https://cloud.githubusercontent.com/assets/10865465/16792837/c43a9596-48e5-11e6-977f-95ea5607e383.png)
![two](https://cloud.githubusercontent.com/assets/10865465/16792838/c43c530e-48e5-11e6-941e-6c1d88f11375.png)

**Comment by Ghayyas** [comment]
@Muhammadmateen  @Attaullah7396

**Comment by Attaullah7396** [comment]
Issue resolved, Now delete is working as well as dropdown menu closing..

**Comment by Muhammadmateen** [comment]
Atta when you resolve the issue assign the label and mani will close this issue after check.

**Comment by Ghayyas** [comment]
Ok if Issue is resolved than close this issue..
